=== diegossilveira/jcors/src/main/resources/jcors-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:c="http://jcors.org/config" targetNamespace="http://jcors.org/config"
	elementFormDefault="qualified">

	<!-- Simple Types -->
	<xs:simpleType name="methodType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CONNECT" />
			<xs:enumeration value="DELETE" />
			<xs:enumeration value="GET" />
			<xs:enumeration value="HEAD" />
			<xs:enumeration value="OPTIONS" />
			<xs:enumeration value="POST" />
			<xs:enumeration value="PUT" />
			<xs:enumeration value="TRACE" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Complex Elements -->
	<xs:complexType name="allowedOriginsType">
		<xs:sequence>
			<xs:element name="origin" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="exposedHeadersType">
		<xs:sequence>
			<xs:element name="header" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="allowedHeadersType">
		<xs:sequence>
			<xs:element name="header" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="allowedMethodsType">
		<xs:sequence>
			<xs:element name="method" type="c:methodType" minOccurs="1"
				maxOccurs="8" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="configurationType">
		<xs:sequence>
			<xs:element name="enableNonCorsRequests" type="xs:boolean"
				default="true" minOccurs="0" maxOccurs="1" />
			<xs:element name="resourcesSupportsCredentials" type="xs:boolean"
				default="true" minOccurs="0" maxOccurs="1" />
			<xs:element name="preflightResultCacheMaxAge" type="xs:integer"
				default="0" minOccurs="0" maxOccurs="1" />
			<xs:element name="allowedOrigins" type="c:allowedOriginsType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="allowedHeaders" type="c:allowedHeadersType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="allowedMethods" type="c:allowedMethodsType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="exposedHeaders" type="c:exposedHeadersType"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<!-- Elements -->
	<xs:element name="configuration" type="c:configurationType" />

</xs:schema>

=== diegossilveira/jcors/src/main/resources/jcors-sample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
*****************************************************************************************************
- This is a sample JCors configuration file.
- Just rename this to jcors.xml and put in your project's classpath.
*****************************************************************************************************
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://jcors.org/config" xsi:schemaLocation="http://jcors.org/config/1.0 jcors-schema.xsd">

	<!--
	************************************************************************************************
	- This is an *optional* tag.
	- Used to define if non-CORS request handling is wanted.
	- The default value is true
	************************************************************************************************
	-->
	<enableNonCorsRequests>true</enableNonCorsRequests>
	
	<!--
	************************************************************************************************
	- This is an *optional* tag. 
	- Used to define if web resources behind the filter support authentication.
	- The default value is true
	************************************************************************************************
	-->
	<resourcesSupportsCredentials>false</resourcesSupportsCredentials>
	
	<!--
	************************************************************************************************
	- This is an *optional* tag. 
	- Configures the amount of seconds the user agent is allowed to cache the result of preflight 
	- requests. A value of 0 disables the cache.
	- The default value is 0 (cache disabled)
	************************************************************************************************
	-->
	<preflightResultCacheMaxAge>300</preflightResultCacheMaxAge>

	<!--
	************************************************************************************************
	- This is an *optional* tag. 
	- Specifies the origin domains allowed by the resources.
	- By default, any domain is allowed
	************************************************************************************************
	-->
	<allowedOrigins>
		<origin>http://mydomain.org</origin>
	</allowedOrigins>

	<!--
	************************************************************************************************
	- This is an *optional* tag. 
	- Indicates which header field names can be used during actual requests.
	- The default, any header is allowed
	************************************************************************************************
	-->
	<allowedHeaders>
		<header>My-Header</header>
	</allowedHeaders>

	<!--
	************************************************************************************************
	- This is an *optional* tag. 
	- Indicates which HTTP methods can be used during actual requests.
	- The default, any method is allowed
	************************************************************************************************
	-->
	<allowedMethods>
		<method>GET</method>
		<method>PUT</method>
		<method>POST</method>
		<method>DELETE</method>
	</allowedMethods>

	<!--
	************************************************************************************************
	- This is an *optional* tag. 
	- Indicates which headers are safe to expose to the API of a CORS API specification.
	- The default, any method is allowed
	************************************************************************************************
	-->
	<exposedHeaders>
		<header>myheader</header>
	</exposedHeaders>

</configuration>
